### ISSUE TITLE
Better screenshot

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/spyglass#6]

**Comment by rodica-andronache** [comment]
@ineagu should I close this?

**Comment by ineagu** [comment]
yep.

On Thu, Apr 7, 2016 at 4:13 PM, Rodica-Elena Andronache <
notifications@github.com> wrote:

> @ineagu <https://github.com/ineagu> should I close this?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeinwp/spyglass/issues/6#issuecomment-206894099>
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com
